// src/routes/login/+page.svelte
<script lang="ts">
	import { login, signup, setToken } from '$lib/api';
	import { auth } from '$lib/stores/auth';
	import { goto } from '$app/navigation';

	let mode = $state<'login' | 'signup'>('login');
	let email = $state('');
	let password = $state('');
	let first_name = $state('');
	let last_name = $state('');
	let error = $state('');
	let loading = $state(false);

	async function handleSubmit(e: Event) {
		e.preventDefault();
		error = '';
		loading = true;

		try {
			if (mode === 'login') {
				const token = await login({ email, password });
				setToken(token.access_token);
			} else {
				await signup({ first_name, last_name, email, password });
				// After signup, login automatically
				const token = await login({ email, password });
				setToken(token.access_token);
			}
			await auth.load();
			goto('/contas');
		} catch (e: any) {
			error = e.message || 'Algo deu errado';
		} finally {
			loading = false;
		}
	}
</script>

<div class="min-h-screen bg-background flex items-center justify-center p-4">
	<div class="w-full max-w-sm">
		<div class="bg-surface border border-border rounded-2xl p-6 shadow-2xl animate-fade-up">
			<div class="text-center mb-6">
				<h1 class="text-2xl font-bold text-text-primary">
					{mode === 'login' ? 'Entrar' : 'Criar conta'}
				</h1>
				<p class="text-muted text-sm mt-1">
					{mode === 'login' ? 'Acesse sua conta' : 'Comece a controlar suas finanças'}
				</p>
			</div>

			{#if error}
				<div class="bg-danger/10 border border-danger/30 text-danger rounded-lg p-3 mb-4 text-sm">
					{error}
				</div>
			{/if}

			<form onsubmit={handleSubmit} class="space-y-4">
				{#if mode === 'signup'}
					<div class="grid grid-cols-2 gap-3">
						<div>
							<label for="first_name" class="block text-sm text-muted mb-1">Nome</label>
							<input
								id="first_name"
								type="text"
								bind:value={first_name}
								required
								class="w-full bg-surface-3 border border-border rounded-lg px-3 py-2 text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-colors"
								placeholder="João"
							/>
						</div>
						<div>
							<label for="last_name" class="block text-sm text-muted mb-1">Sobrenome</label>
							<input
								id="last_name"
								type="text"
								bind:value={last_name}
								required
								class="w-full bg-surface-3 border border-border rounded-lg px-3 py-2 text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-colors"
								placeholder="Silva"
							/>
						</div>
					</div>
				{/if}

				<div>
					<label for="email" class="block text-sm text-muted mb-1">Email</label>
					<input
						id="email"
						type="email"
						bind:value={email}
						required
						class="w-full bg-surface-3 border border-border rounded-lg px-3 py-2 text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-colors"
						placeholder="seu@email.com"
					/>
				</div>

				<div>
					<label for="password" class="block text-sm text-muted mb-1">Senha</label>
					<input
						id="password"
						type="password"
						bind:value={password}
						required
						minlength={6}
						class="w-full bg-surface-3 border border-border rounded-lg px-3 py-2 text-text-primary placeholder:text-text-secondary focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-colors"
						placeholder="••••••••"
					/>
				</div>

				<button
					type="submit"
					disabled={loading}
					class="w-full bg-primary hover:bg-primary-hover text-white rounded-lg py-2.5 font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
				>
					{loading ? 'Aguarde...' : mode === 'login' ? 'Entrar' : 'Criar conta'}
				</button>
			</form>

			<div class="mt-4 text-center">
				<button
					onclick={() => { mode = mode === 'login' ? 'signup' : 'login'; error = ''; }}
					class="text-sm text-muted hover:text-text-primary transition-colors"
				>
					{mode === 'login' ? 'Não tem uma conta? Criar' : 'Já tem uma conta? Entrar'}
				</button>
			</div>

			{#if mode === 'login'}
				<div class="mt-3 text-center">
					<button
						class="text-xs text-text-secondary hover:text-muted transition-colors"
						title="Funcionalidade em breve"
						disabled
					>
						Esqueci minha senha
					</button>
				</div>
			{/if}
		</div>
	</div>
</div>

// src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Tab = "login" | "signup";
type Feedback = { type: "error" | "success"; message: string };

export default function LoginPage() {
  const router = useRouter();
  const supabase = createClient();

  const [tab, setTab] = useState<Tab>("login");
  const [loading, setLoading] = useState(false);
  const [feedback, setFeedback] = useState<Feedback | null>(null);

  // Login
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  // Signup
  const [signupEmail, setSignupEmail] = useState("");
  const [signupPassword, setSignupPassword] = useState("");
  const [signupConfirm, setSignupConfirm] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [username, setUsername] = useState("");

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setFeedback(null);

    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) {
      setFeedback({ type: "error", message: error.message });
      setLoading(false);
    } else {
      router.push("/transactions");
    }
  }

  async function handleSignup(e: React.FormEvent) {
    e.preventDefault();
    setFeedback(null);

    if (signupPassword !== signupConfirm) {
      setFeedback({ type: "error", message: "As senhas não coincidem." });
      return;
    }

    setLoading(true);

    const { data, error } = await supabase.auth.signUp({
      email: signupEmail,
      password: signupPassword,
      options: {
        data: { username, first_name: firstName, last_name: lastName },
      },
    });

    if (error) {
      setFeedback({ type: "error", message: error.message });
      setLoading(false);
      return;
    }

    if (!data.session) {
      setFeedback({
        type: "success",
        message: "Cadastro realizado! Verifique seu e-mail para confirmar a conta.",
      });
      setLoading(false);
      return;
    }

    router.push("/transactions");
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background">
      <div className="w-full max-w-sm">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold">
            <span className="text-primary">Loot</span> Control
          </h1>
          <p className="text-text-secondary text-sm mt-1">Controle financeiro sem atrito</p>
        </div>

        {/* Tabs */}
        <div className="flex mb-4 bg-surface rounded-xl border border-border p-1">
          {(["login", "signup"] as Tab[]).map((t) => (
            <button
              key={t}
              onClick={() => { setTab(t); setFeedback(null); }}
              className={`flex-1 py-2 text-sm font-medium rounded-lg transition-colors ${
                tab === t
                  ? "bg-primary text-white"
                  : "text-text-secondary hover:text-text-primary"
              }`}
            >
              {t === "login" ? "Entrar" : "Cadastrar"}
            </button>
          ))}
        </div>

        <div className="bg-surface rounded-xl border border-border p-6">
          {/* Feedback */}
          {feedback && (
            <div
              className={`mb-4 text-xs rounded-lg px-3 py-2 border ${
                feedback.type === "error"
                  ? "text-danger bg-danger/10 border-danger/20"
                  : "text-accent bg-accent/10 border-accent/20"
              }`}
            >
              {feedback.message}
            </div>
          )}

          {tab === "login" ? (
            <form onSubmit={handleLogin} className="space-y-4">
              <Field label="Email">
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  placeholder="seu@email.com"
                  className={inputClass}
                />
              </Field>

              <Field label="Senha">
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  placeholder="••••••••"
                  className={inputClass}
                />
              </Field>

              <SubmitButton loading={loading} label="Entrar" loadingLabel="Entrando..." />
            </form>
          ) : (
            <form onSubmit={handleSignup} className="space-y-4">
              <div className="grid grid-cols-2 gap-3">
                <Field label="Nome">
                  <input
                    type="text"
                    value={firstName}
                    onChange={(e) => setFirstName(e.target.value)}
                    required
                    placeholder="João"
                    className={inputClass}
                  />
                </Field>
                <Field label="Sobrenome">
                  <input
                    type="text"
                    value={lastName}
                    onChange={(e) => setLastName(e.target.value)}
                    required
                    placeholder="Silva"
                    className={inputClass}
                  />
                </Field>
              </div>

              <Field label="Username">
                <input
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                  placeholder="joaosilva"
                  className={inputClass}
                />
              </Field>

              <Field label="Email">
                <input
                  type="email"
                  value={signupEmail}
                  onChange={(e) => setSignupEmail(e.target.value)}
                  required
                  placeholder="seu@email.com"
                  className={inputClass}
                />
              </Field>

              <Field label="Senha">
                <input
                  type="password"
                  value={signupPassword}
                  onChange={(e) => setSignupPassword(e.target.value)}
                  required
                  minLength={6}
                  placeholder="mínimo 6 caracteres"
                  className={inputClass}
                />
              </Field>

              <Field label="Confirmar senha">
                <input
                  type="password"
                  value={signupConfirm}
                  onChange={(e) => setSignupConfirm(e.target.value)}
                  required
                  placeholder="••••••••"
                  className={inputClass}
                />
              </Field>

              <SubmitButton loading={loading} label="Criar conta" loadingLabel="Criando..." />
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

const inputClass =
  "w-full bg-surface-2 border border-border rounded-lg px-3 py-2.5 text-sm text-text-primary placeholder:text-muted focus:outline-none focus:border-primary transition-colors";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="block text-xs text-text-secondary mb-1.5 uppercase tracking-wider">
        {label}
      </label>
      {children}
    </div>
  );
}

function SubmitButton({
  loading,
  label,
  loadingLabel,
}: {
  loading: boolean;
  label: string;
  loadingLabel: string;
}) {
  return (
    <button
      type="submit"
      disabled={loading}
      className="w-full bg-primary hover:bg-primary-hover disabled:opacity-50 text-white font-medium py-2.5 rounded-lg text-sm transition-colors"
    >
      {loading ? loadingLabel : label}
    </button>
  );
}
